# Generated by Django 5.1.5 on 2025-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(max_length=255),
        ),
    ]
