# Generated by Django 5.1.5 on 2025-04-06 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Client',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_num', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('geo_location', models.CharField(max_length=255)),
                ('unit_apt_num', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('payment_option', models.CharField(choices=[('Paypal', 'Paypal'), ('Debit/Credit', 'Debit/Credit')], default='Paypal', max_length=50)),
                ('identification', models.CharField(default='none', max_length=255)),
                ('dark_mode', models.BooleanField(default=False)),
                ('language', models.CharField(default='English', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Description',
            fields=[
                ('cstmr_descr_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('tool', models.CharField(max_length=255)),
                ('request_description', models.TextField()),
                ('request_price', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('geo_location', models.CharField(max_length=255)),
                ('unit_apt_num', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('personal_business', models.CharField(max_length=255)),
                ('request_size', models.CharField(max_length=255)),
                ('people_amount', models.CharField(max_length=255)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.customer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user_client')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('location_address', models.TextField()),
                ('location_city', models.CharField(max_length=255)),
                ('location_state', models.CharField(max_length=255)),
                ('location_unit_num', models.CharField(max_length=255)),
                ('location_zip_code', models.CharField(max_length=255)),
                ('geo_location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user_client')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Rating',
            fields=[
                ('cstmr_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(choices=[(1, '1_STAR'), (2, '2_STAR'), (3, '3_STAR'), (4, '4_STAR'), (5, '5_STAR')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user_client')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.user_client'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.user_client')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('tool', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_price', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('geo_location', models.CharField(max_length=255)),
                ('unit_apt_num', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('personal_business', models.CharField(max_length=255)),
                ('job_size', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user_client')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Description',
            fields=[
                ('worker_description_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Rating',
            fields=[
                ('worker_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(choices=[(1, '1_STAR'), (2, '2_STAR'), (3, '3_STAR'), (4, '4_STAR'), (5, '5_STAR')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user_client')),
            ],
        ),
    ]
