# Generated by Django 5.1.5 on 2025-04-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_request_rejection_reason_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='job_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
